apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-nginx
  namespace: openshift-gitops-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-nginx-service
  namespace: openshift-gitops-apps
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitops-nginx-route
  namespace: openshift-gitops-apps
spec:
  to:
    kind: Service
    name: gitops-nginx-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
